services:
  - type: web
    name: chat-app
    env: java
    region: oregon
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080